'use client';
import { useEffect, useRef, useState } from 'react';
import { dispatchAction } from '@/app/operations-actions';
import { Avatar, Pill } from './OperationsUI';
import type { CrewMember, DispatchJob } from '@/lib/operations';

export function DispatchBoard({jobs,crew,date,crewFilter}:{jobs:DispatchJob[];crew:CrewMember[];date:string;crewFilter?:number}) {
 const [selected,setSelected]=useState<DispatchJob|null>(null),[member,setMember]=useState('');
 const dialog=useRef<HTMLDialogElement>(null);
 const active=crew.filter(m=>m.active && (!crewFilter || m.id===crewFilter));
 const today=jobs.filter(j=>j.scheduledStart?.slice(0,10)===date && j.status!=='cancelled');
 const queue=jobs.filter(j=>!['completed','cancelled'].includes(j.status)&&(!j.scheduledStart||!j.teamMemberId));
 useEffect(()=>{if(selected)dialog.current?.showModal();else dialog.current?.close();},[selected]);
 function open(job:DispatchJob,memberId?:number){setSelected(job);setMember(String(memberId??job.teamMemberId??''));}
 function drop(e:React.DragEvent,memberId:number){e.preventDefault();const job=jobs.find(j=>j.id===Number(e.dataTransfer.getData('text/plain')));if(job)open(job,memberId);}
 return <><div className="ops-dispatch-layout"><section className="ops-dispatch-queue"><div className="ops-section-head"><h2>Needs a place</h2><Pill>{queue.length}</Pill></div><p className="tiny">Drag onto a crew lane or choose a job to schedule.</p>{queue.length?queue.map(job=><button type="button" className="ops-queue-job" key={job.id} onClick={()=>open(job)} draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(job.id))}><span className="row-between"><span className="tiny">{job.durationMinutes} MIN</span>{job.priority!=='normal'?<Pill tone="warn">{job.priority}</Pill>:null}</span><strong>{job.title}</strong><span>{job.customerName}</span><small>{job.serviceCity||job.serviceLine1||'Address to confirm'}</small></button>):<div className="ops-small-empty">Everything has a place.<br/>New requests appear here once they become jobs.</div>}</section>
 <section className="ops-dispatch-main"><div className="ops-board-top"><div><span className="ops-eyebrow">DISPATCH BOARD</span><h2>The right person. The right time.</h2></div><a href="/team" className="btn btn-secondary btn-sm">Manage crew</a></div><div className="ops-timeline-scroll"><div className="ops-timeline"><div className="ops-hours"><span>Crew</span><div>{[7,9,11,13,15,17,19].map(h=><span key={h}>{h>12?h-12:h}{h>=12?'pm':'am'}</span>)}</div></div>{active.map(person=>{const assigned=today.filter(j=>j.teamMemberId===person.id);const locations=assigned.filter(j=>j.serviceLine1).map(j=>`${j.serviceLine1}, ${j.serviceCity}`);const maps=locations.length?`https://www.google.com/maps/dir/${locations.map(encodeURIComponent).join('/')}`:'';return <div className="ops-crew-lane" key={person.id}><div className="ops-crew-label"><Avatar name={person.name} color={person.color}/><div><strong>{person.name}</strong><small>{assigned.length} jobs · {Math.round(assigned.reduce((s,j)=>s+j.durationMinutes,0)/6)/10}h</small>{maps?<a className="tiny" href={maps} target="_blank" rel="noreferrer">Open route ↗</a>:null}</div></div><div className="ops-track" onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,person.id)} aria-label={`Schedule for ${person.name}`}><div className="ops-track-grid"/>{assigned.map(job=>{const stamp=job.scheduledStart||'';const minute=Number(stamp.slice(11,13))*60+Number(stamp.slice(14,16));const left=Math.max(0,Math.min(96,(minute-420)/780*100));const width=Math.max(5,Math.min(100-left,job.durationMinutes/780*100));return <button key={job.id} className={`ops-scheduled-job ${job.status==='completed'?'is-complete':''}`} style={{left:`${left}%`,width:`${width}%`,borderColor:person.color}} onClick={()=>open(job)} draggable={job.status!=='completed'} onDragStart={e=>e.dataTransfer.setData('text/plain',String(job.id))} title={`${stamp.slice(11,16)} · ${job.title} · ${job.customerName}`}><strong>{job.title}</strong><span>{stamp.slice(11,16)} · {job.customerName}</span></button>;})}{!assigned.length?<span className="ops-lane-hint">Room for the next job</span>:null}</div></div>;})}</div></div>{!active.length?<div className="ops-small-empty">Add an active crew member to start dispatching.</div>:null}
 <div className="ops-agenda"><h3>Day’s appointments</h3>{today.filter(j=>!crewFilter||j.teamMemberId===crewFilter).map(job=><button className="ops-agenda-row" key={job.id} onClick={()=>open(job)}><time>{job.scheduledStart?.slice(11,16)}</time><span><strong>{job.title}</strong><small>{job.customerName} · {job.technicianName||'Unassigned'}</small></span><Pill tone={job.status==='completed'?'good':job.priority==='urgent'?'bad':'neutral'}>{job.status.replace('_',' ')}</Pill><b>↗</b></button>)}{!today.length?<p className="muted">No appointments for this day.</p>:null}</div></section></div>
 <dialog className="ops-dialog" ref={dialog} onCancel={()=>setSelected(null)} onClose={()=>setSelected(null)}>{selected?<><div className="ops-dialog-head"><div><span className="ops-eyebrow">SCHEDULE JOB</span><h2>{selected.title}</h2><p>{selected.customerName}</p></div><button className="icon-btn" type="button" onClick={()=>setSelected(null)} aria-label="Close scheduling">×</button></div>{selected.status==='completed'?<><p>This job is complete.</p><a className="btn" href={`/jobs/${selected.id}`}>Open job</a></>:<form action={dispatchAction} className="form-grid"><input type="hidden" name="job_id" value={selected.id}/><input type="hidden" name="version" value={selected.scheduleVersion}/><input type="hidden" name="next" value={`/dispatch?date=${date}`}/><div className="field full"><label htmlFor="dispatch-member">Crew member</label><select id="dispatch-member" name="member_id" value={member} onChange={e=>setMember(e.target.value)} required><option value="">Choose a crew member</option>{crew.filter(m=>m.active).map(m=><option value={m.id} key={m.id}>{m.name}{m.skills?` · ${m.skills}`:''}</option>)}</select></div><div className="field"><label htmlFor="dispatch-start">Start time</label><input id="dispatch-start" name="start" type="datetime-local" defaultValue={selected.scheduledStart?.slice(0,16)||`${date}T09:00`} required/></div><div className="field"><label htmlFor="dispatch-duration">Duration (minutes)</label><input id="dispatch-duration" name="duration" type="number" min={15} max={1440} defaultValue={selected.durationMinutes} required/></div><div className="field"><label htmlFor="dispatch-priority">Priority</label><select id="dispatch-priority" name="priority" defaultValue={selected.priority}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></div><p className="help full">Sere checks the latest schedule before saving. Appointment times use your business’s local time.</p><div className="form-actions"><a href={`/jobs/${selected.id}`} className="btn btn-secondary">Open job</a><button className="btn">Save assignment</button></div></form>}</>:null}</dialog></>;
}
