'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { putUpdate, queuedUpdates, removeUpdate, type PendingFieldUpdate } from '@/lib/field-queue';
import type { ChecklistItem } from '@/lib/operations';

async function photoData(file:File):Promise<string>{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Choose a JPEG, PNG, or WebP photo.');
 if(file.size>15_000_000)throw new Error('Choose a photo under 15 MB.');
 const bitmap=await createImageBitmap(file);const scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
 const result=canvas.toDataURL('image/jpeg',0.65);if(result.length>500000)throw new Error('This photo is still too large. Try a smaller image.');return result;
}
export function FieldCapture({organizationId,userId,jobId,checklist}:{organizationId:number;userId:number;jobId:number;checklist:ChecklistItem[]}) {
 const router=useRouter();const [pending,setPending]=useState<PendingFieldUpdate[]>([]),[online,setOnline]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[kind,setKind]=useState('note');const syncing=useRef(false);
 const reload=useCallback(async()=>{setPending(await queuedUpdates(organizationId,userId));},[organizationId,userId]);
 const sync=useCallback(async()=>{
  if(syncing.current||!navigator.onLine)return;syncing.current=true;let saved=0;
  try{const updates=await queuedUpdates(organizationId,userId);for(const update of updates){
   if(update.error)continue;
   let response:Response;try{response=await fetch('/api/field',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(update),signal:AbortSignal.timeout(20000)});}catch{break;}
   const result=await response.json().catch(()=>({error:'Could not read the response. Your update remains on this device.'}));
   if(response.ok){await removeUpdate(update.mutationId);saved++;}else{await putUpdate({...update,error:result.error||'Could not sync this update.'});if([401,403].includes(response.status))break;}
  }}catch{setNotice('Device storage is unavailable. Keep this screen open and reconnect before leaving.');}finally{syncing.current=false;await reload().catch(()=>{});if(saved){setNotice(`${saved} ${saved===1?'update':'updates'} saved to the job.`);router.refresh();}}
 },[organizationId,userId,reload,router]);
 useEffect(()=>{setOnline(navigator.onLine);reload().catch(()=>setNotice('Enable browser storage to save field updates.'));void sync();const connected=()=>{setOnline(navigator.onLine);if(navigator.onLine)void sync();};window.addEventListener('online',connected);window.addEventListener('offline',connected);const timer=setInterval(()=>void sync(),15000);return()=>{clearInterval(timer);window.removeEventListener('online',connected);window.removeEventListener('offline',connected);};},[reload,sync]);
 async function enqueue(data:Partial<PendingFieldUpdate>){if(pending.length>=100)throw new Error('Sync pending work before adding more updates.');await putUpdate({organizationId,userId,jobId,mutationId:crypto.randomUUID(),kind:'note',body:'',minutes:0,capturedAt:new Date().toISOString(),...data});await reload();setNotice('Saved on this device.');void sync();}
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);setBusy(true);try{const body=String(data.get('body')||'').trim();const minutes=Number(data.get('minutes')||0);if(kind!=='photo'&&!body)throw new Error('Add a note about the work.');if(kind==='time'&&(!Number.isInteger(minutes)||minutes<1||minutes>1440))throw new Error('Enter 1 to 1440 minutes.');const photo=data.get('photo');if(kind==='photo'&&(!(photo instanceof File)||!photo.size))throw new Error('Choose a photo.');await enqueue({kind,body:kind==='photo'?await photoData(photo as File):body,minutes});form.reset();}catch(error){setNotice(error instanceof Error?error.message:'Could not save.');}finally{setBusy(false);}}
 const jobPending=pending.filter(p=>p.jobId===jobId);
 return <div className="ops-field-capture"><div className={`ops-sync-status ${online?'':'is-offline'}`} role="status"><span className="ops-live-dot"/><strong>{online?'Connected':'Working offline'}</strong><span>{pending.length?`${pending.length} pending across your jobs`:'All field updates synced'}</span>{pending.length?<button type="button" className="btn btn-ghost btn-sm" onClick={()=>void sync()}>Sync now</button>:null}</div>
 <p className="tiny">Keep this field screen open when reception drops. Notes, time, photos, and checklist updates stay on this device until Sere confirms they’re saved.</p>
 {checklist.length?<section className="ops-checklist"><h3>Before you finish</h3>{checklist.map(item=>{const queued=jobPending.find(p=>p.kind==='checklist'&&p.checklistId===item.id);return <label key={item.id} className="ops-checklist-row"><input type="checkbox" checked={queued?Boolean(queued.done):Boolean(item.done)} disabled={Boolean(queued)} onChange={e=>enqueue({kind:'checklist',checklistId:item.id,done:e.target.checked,version:item.version}).catch(error=>setNotice(error.message))}/><span>{item.label}</span>{queued?<small>Pending sync</small>:null}</label>;})}</section>:null}
 <form onSubmit={submit}><div className="ops-capture-tabs" role="group" aria-label="Field update type">{['note','time','photo'].map(k=><button type="button" key={k} className={kind===k?'active':''} onClick={()=>setKind(k)}>{k==='note'?'Job note':k==='time'?'Log time':'Add photo'}</button>)}</div>{kind==='photo'?<div className="field"><label htmlFor="field-photo">Job photo</label><input id="field-photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" required/><p className="help">Photos are resized for the job record.</p></div>:<div className="field"><label htmlFor="field-note">{kind==='time'?'Work performed':'What happened on this visit?'}</label><textarea id="field-note" name="body" rows={4} maxLength={kind==='time'?1000:6000} required placeholder="What you found, what you did, and anything the next tech should know."/></div>}{kind==='time'?<div className="field mt-1"><label htmlFor="field-minutes">Minutes worked</label><input id="field-minutes" type="number" name="minutes" min={1} max={1440} required/></div>:null}<div className="row-between mt-2"><p className="tiny" role="status">{notice}</p><button className="btn" disabled={busy}>{busy?'Saving…':'Save update'}</button></div></form>
 {pending.length?<section className="ops-pending-list"><h3>Pending on this device</h3>{pending.map(update=><div key={update.mutationId}><span><strong>{update.kind==='photo'?'Photo':update.kind==='checklist'?'Checklist change':update.body.slice(0,90)}</strong><small>Job #{update.jobId}{update.error?` · ${update.error}`:' · Waiting to sync'}</small></span>{update.error?<button className="btn btn-secondary btn-sm" onClick={async()=>{await putUpdate({...update,error:undefined});await reload();void sync();}}>Retry</button>:null}<button className="btn btn-ghost btn-sm" onClick={async()=>{if(window.confirm('Discard this unsynced field update? It will not be saved to the job.')){await removeUpdate(update.mutationId);await reload();}}}>Discard</button></div>)}</section>:null}</div>;
}
