import { automationRuleAction, cancelFollowUpAction, prepareFollowUpsAction, sendFollowUpAction } from '@/app/operations-actions';
import { Shell } from '@/components/Shell';
import { Banner, Stat } from '@/components/ui';
import { Field, OperationsNav, OpsEmpty, Pill } from '@/components/OperationsUI';
import { loadApp } from '@/lib/page';
import { getOutbox, getRules } from '@/lib/operations-automations';
import { RULES, type RuleKind } from '@/lib/operations-validation';
import { emailConfig } from '@/lib/integrations';
import { prettyWhen } from '@/lib/labels';

export default async function AutomationsPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string}>}) {
 const {org,shell}=await loadApp(),q=await searchParams;const [rules,outbox,config]=await Promise.all([getRules(org.id),getOutbox(org.id),emailConfig(org.id)]);
 const disabledSend=!config||shell.isDemo||org.operatingMode==='sandbox';
 return <Shell {...shell} path="/automations" title="Make follow-through a habit." sub={<p className="page-sub">Sere prepares the follow-ups. You review and send them.</p>} actions={<form action={prepareFollowUpsAction}><button className="btn">Prepare follow-ups</button></form>}><OperationsNav active="/automations"/><Banner error={q.error} ok={q.ok}/>
 <div className="grid grid-3"><Stat label="Rules enabled" value={String(rules.filter(r=>r.enabled).length)} note="Preparing customer follow-ups"/><Stat label="Ready for review" value={String(outbox.filter(m=>m.status==='draft').length)} note="In the recent outbox"/><Stat label="Sent" value={String(outbox.filter(m=>m.status==='sent').length)} note="In the most recent 100 messages"/></div>
 {!config?<div className="ops-callout"><div><strong>Connect your business email to send.</strong><p>You can prepare and review drafts now.</p></div><a className="btn btn-secondary btn-sm" href="/settings?tab=integrations">Connect email</a></div>:null}
 <section className="ops-section"><div className="ops-section-head"><h2>Your follow-up rules</h2><span className="muted">Nothing sends without review</span></div><div className="ops-plan-grid">{(Object.keys(RULES) as RuleKind[]).map(kind=>{const rule=rules.find(r=>r.kind===kind);return <form className="ops-rule-card" action={automationRuleAction} key={kind}><input type="hidden" name="kind" value={kind}/><div className="row-between"><Pill tone={rule?.enabled?'good':'neutral'}>{rule?.enabled?'Enabled':'Off'}</Pill><label className="ops-switch"><input type="checkbox" name="enabled" defaultChecked={Boolean(rule?.enabled)}/><span>Enabled</span></label></div><h3>{RULES[kind].name}</h3><p>{RULES[kind].detail}</p><Field label="Days after due / sent date" name="delay_days" type="number" min="0" max="90" defaultValue={rule?.delayDays??3}/><button className="btn btn-secondary btn-sm">Save rule</button></form>;})}</div></section>
 <section className="ops-section"><div className="ops-section-head"><h2>Follow-up outbox</h2><span className="muted">Most recent 100 messages</span></div>{outbox.length?<div className="ops-outbox">{outbox.map(m=><details className="ops-message" key={m.id} open={m.status==='draft'}><summary><div><strong>{m.subject}</strong><span>{m.recipient} · {prettyWhen(m.createdAt)}</span></div><Pill tone={m.status==='sent'?'good':['uncertain','failed'].includes(m.status)?'warn':'neutral'}>{m.status}</Pill></summary><div className="ops-message-body"><p className="ops-preline">{m.body}</p>{m.error?<p className="ops-message-error">{m.error}</p>:null}{['sending','uncertain'].includes(m.status)?<p className="help">Confirm delivery in your email provider before following up manually. Sere will not automatically resend this message.</p>:null}{m.status==='draft'?<div className="ops-card-actions"><form action={sendFollowUpAction}><input type="hidden" name="id" value={m.id}/><button className="btn btn-sm" disabled={disabledSend}>Send this follow-up</button></form><form action={cancelFollowUpAction}><input type="hidden" name="id" value={m.id}/><button className="btn btn-secondary btn-sm">Cancel draft</button></form></div>:null}{m.providerId?<p className="help">Delivery reference: {m.providerId}</p>:null}</div></details>)}</div>:<OpsEmpty title="No follow-ups waiting." body="Enable a rule, then prepare follow-ups. Paid invoices, accepted estimates, and paused plans are checked again before a message sends."/>}</section></Shell>;
}
