import { bookingSettingsAction, convertRequestAction, saveRequestAction, updateRequestAction } from '@/app/operations-actions';
import { Shell } from '@/components/Shell';
import { Banner, Stat } from '@/components/ui';
import { Avatar, Field, FormPanel, OperationsNav, OpsEmpty, Pill, SelectField, Submit, TextField } from '@/components/OperationsUI';
import { loadApp } from '@/lib/page';
import { getOperationsSettings, getRequests } from '@/lib/operations';
import { REQUEST_STATUSES } from '@/lib/operations-validation';
import { prettyDate, label } from '@/lib/labels';
import { token } from '@/lib/db';

export default async function RequestsPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string;new?:string;stage?:string}>}) {
  const {org,shell}=await loadApp(); const q=await searchParams;
  const [requests,settings]=await Promise.all([getRequests(org.id),getOperationsSettings(org.id)]);
  const stage=REQUEST_STATUSES.includes(q.stage as typeof REQUEST_STATUSES[number])?q.stage:"new";
  const open=requests.filter(r=>!['lost','booked'].includes(r.status));
  return <Shell {...shell} path="/requests" title="Requests" sub={<p className="page-sub">One place for new calls, website requests, and the next conversation.</p>} actions={<a className="btn" href="/requests?new=1">+ New request</a>}>
    <OperationsNav active="/requests"/><Banner error={q.error} ok={q.ok}/>
    <div className="grid grid-4"><Stat label="Open requests" value={String(open.length)} note="Ready for the next step"/><Stat label="Needs a first response" value={String(requests.filter(r=>r.status==='new').length)} note="Start the conversation"/><Stat label="Converted to jobs" value={String(requests.filter(r=>r.jobId).length)} tone="good" note="All-time requests"/><Stat label="Online requests" value={settings.bookingEnabled?'Open':'Closed'} note={settings.bookingEnabled?'Your request page is accepting work':'Enable your booking link below'}/></div>
    <FormPanel title="Add a request" open={q.new==='1'}><form action={saveRequestAction} className="form-grid">
      <input type="hidden" name="submission_key" value={token()}/><Field label="Customer name" name="name" required maxLength={120}/><Field label="Service needed" name="service" required placeholder="AC not cooling" maxLength={200}/><Field label="Email" name="email" type="email"/><Field label="Phone" name="phone" type="tel"/><Field label="Service address" name="address"/><Field label="Preferred date" name="preferred_date" type="date"/><SelectField label="Priority" name="priority" defaultValue="normal"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></SelectField><TextField label="What does the customer need?" name="description"/><Submit>Add request</Submit>
    </form></FormPanel>
    <div className="ops-section-head"><div><span className="ops-eyebrow">SALES PIPELINE</span><h2>From first hello to the next job.</h2></div><span className="tiny">{requests.length} total requests</span></div>
    <nav className="mobile-request-stages" aria-label="Request stage">{REQUEST_STATUSES.map(s=><a key={s} className={stage===s?"active":""} aria-current={stage===s?"page":undefined} href={`/requests?stage=${s}`}>{label(s)} <span>{requests.filter(r=>r.status===s).length}</span></a>)}</nav>
    <div className="ops-pipeline" data-mobile-stage={stage}>{REQUEST_STATUSES.map(stage=>{const items=requests.filter(r=>r.status===stage);return <section key={stage} className={`ops-lane ops-lane-${stage}`}><div className="ops-lane-title"><span className="ops-stage-dot"/><h3>{label(stage)}</h3><span>{items.length}</span></div>{items.length?items.map(r=><article key={r.id} className="ops-request-card"><div className="row-between"><span className="tiny">{r.source==='website'?'Website':'Office'} · {prettyDate(r.createdAt)}</span>{r.priority!=='normal'?<Pill tone={r.priority==='urgent'?'bad':'warn'}>{label(r.priority)}</Pill>:null}</div><h3>{r.service}</h3><div className="ops-person"><Avatar name={r.name}/><span><strong>{r.name}</strong><small>{r.address||'Address to confirm'}</small></span></div><details className="ops-record-details"><summary>Request details</summary><p>{r.description||'No additional details.'}</p><p>{r.preferredDate?`Preferred: ${prettyDate(r.preferredDate)}`:'Date to confirm'}</p><div className="col">{r.email?<a href={`mailto:${r.email}`}>{r.email}</a>:null}{r.phone?<a href={`tel:${r.phone}`}>{r.phone}</a>:null}</div></details>{r.jobId?<a className="btn btn-secondary btn-sm btn-block" href={`/jobs/${r.jobId}`}>Open job →</a>:r.estimateId?<a className="btn btn-secondary btn-sm btn-block" href={`/estimates/${r.estimateId}`}>Open linked estimate →</a>:<><form action={convertRequestAction} className="ops-card-actions"><input type="hidden" name="id" value={r.id}/><button className="btn btn-secondary btn-sm" name="target" value="estimate">Estimate</button><button className="btn btn-sm" name="target" value="job">Create job</button></form><form action={updateRequestAction} className="row mt-1"><input type="hidden" name="id" value={r.id}/><select className="input" name="status" defaultValue={r.status} aria-label={`Stage for ${r.name}`}>{REQUEST_STATUSES.filter(s=>s!=='booked').map(s=><option key={s} value={s}>{label(s)}</option>)}</select><button className="btn btn-ghost btn-sm">Move</button></form></>}</article>):<p className="ops-lane-empty">No {stage} requests</p>}</section>;})}</div>
    {!requests.length?<OpsEmpty title="Your next job starts here." body="Add a phone request above or open your online request page below. New requests stay linked to the customer and job as work moves forward."/>:null}
    <FormPanel title="Online request page"><form action={bookingSettingsAction} className="form-grid"><div className="field full"><label className="ops-check"><input type="checkbox" name="booking_enabled" defaultChecked={Boolean(settings.bookingEnabled)}/> Accept online service requests</label><p className="help">Customers request a visit. Your office confirms the time.</p></div><Field label="Service area" name="service_area" defaultValue={settings.serviceArea} placeholder="Fort Myers and Cape Coral"/><TextField label="Welcome message" name="booking_intro" defaultValue={settings.bookingIntro}/><div className="field full"><a href={`/book/${org.slug}`} target="_blank" rel="noreferrer">Open your customer request page ↗</a></div><Submit>Save request page</Submit></form></FormPanel>
  </Shell>;
}
