import { saveCrewAction } from '@/app/operations-actions';
import { Shell } from '@/components/Shell';
import { Banner, Stat } from '@/components/ui';
import { Avatar, Field, FormPanel, OperationsNav, OpsEmpty, Pill, SelectField, Submit } from '@/components/OperationsUI';
import { loadApp } from '@/lib/page';
import { getCrew, getDispatchJobs } from '@/lib/operations';
import { formatMoney, centsToInput } from '@/lib/money';

export default async function TeamPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string;edit?:string;new?:string}>}) {
 const {org,shell}=await loadApp(),q=await searchParams; const [crew,jobs]=await Promise.all([getCrew(org.id),getDispatchJobs(org.id)]);const editing=crew.find(m=>m.id===Number(q.edit));const today=new Date().toISOString().slice(0,10);
 return <Shell {...shell} path="/team" title="Good work starts with your crew." sub={<p className="page-sub">People, skills, and the work ahead of them.</p>} actions={<a className="btn" href="/team?new=1">+ Add crew member</a>}><OperationsNav active="/team"/><Banner error={q.error} ok={q.ok}/><div className="grid grid-3"><Stat label="Active crew" value={String(crew.filter(m=>m.active).length)} note="Available to dispatch"/><Stat label="Assigned today" value={String(jobs.filter(j=>j.scheduledStart?.startsWith(today)&&j.teamMemberId&&j.status!=='cancelled').length)} note="Jobs on the board"/><Stat label="Needs assignment" value={String(jobs.filter(j=>!j.teamMemberId&&!['completed','cancelled'].includes(j.status)).length)} note="Review the dispatch queue"/></div>
 <FormPanel title={editing?`Edit ${editing.name}`:'Add a crew member'} open={Boolean(editing)||q.new==='1'}><form action={saveCrewAction} className="form-grid">{editing?<input type="hidden" name="id" value={editing.id}/>:null}<Field label="Name" name="name" defaultValue={editing?.name} required maxLength={120}/><Field label="Email" name="email" type="email" defaultValue={editing?.email}/><Field label="Phone" name="phone" type="tel" defaultValue={editing?.phone}/><Field label="Skills and certifications" name="skills" defaultValue={editing?.skills} placeholder="HVAC, EPA 608, installations"/><Field label="Loaded hourly cost" name="hourly_cost" inputMode="decimal" defaultValue={centsToInput(editing?.hourlyCostCents||0)}/><Field label="Dispatch color" name="color" type="color" defaultValue={editing?.color||'#7259e8'}/><SelectField label="Availability" name="active" defaultValue={editing?.active??1}><option value="1">Active</option><option value="0">Inactive</option></SelectField><p className="help full">This adds a crew profile for scheduling. It does not create a sign-in account.</p><Submit>Save crew member</Submit></form></FormPanel>
 <div className="ops-team-grid">{crew.map(m=>{const assigned=jobs.filter(j=>j.teamMemberId===m.id&&!['completed','cancelled'].includes(j.status));return <article className="ops-team-card" key={m.id}><div className="row-between"><Avatar name={m.name} color={m.color}/><Pill tone={m.active?'good':'neutral'}>{m.active?'Active':'Inactive'}</Pill></div><h2>{m.name}</h2><p className="muted">{m.skills||'Add skills to help your dispatcher choose the right person.'}</p><div className="ops-team-metrics"><div><strong>{assigned.length}</strong><span>upcoming jobs</span></div><div><strong>{formatMoney(m.hourlyCostCents)}</strong><span>cost / hour</span></div></div><div className="ops-card-actions"><a className="btn btn-secondary btn-sm" href={`/dispatch?crew=${m.id}`}>View schedule</a><a className="btn btn-ghost btn-sm" href={`/team?edit=${m.id}`}>Edit profile</a></div></article>;})}</div>{!crew.length?<OpsEmpty title="Meet your crew." body="Add the people you dispatch. Their assignments, colors, and availability will appear on the schedule."/>:null}</Shell>;
}
