import { moveStockAction, saveInventoryAction } from '@/app/operations-actions';
import { Shell } from '@/components/Shell';
import { Banner, Stat } from '@/components/ui';
import { Field, FormPanel, OperationsNav, OpsEmpty, Pill, SelectField, Submit } from '@/components/OperationsUI';
import { loadApp } from '@/lib/page';
import { getDispatchJobs, getInventory, rows } from '@/lib/operations';
import { token } from '@/lib/db';
import { formatMoney } from '@/lib/money';
import { prettyDate } from '@/lib/labels';

export default async function InventoryPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string;new?:string;item?:string}>}) {
 const {org,shell}=await loadApp(),q=await searchParams;
 const [items,jobs,movements]=await Promise.all([getInventory(org.id),getDispatchJobs(org.id),rows<{id:number;name:string;jobId:number|null;delta:number;note:string;createdAt:string}>('SELECT m.*,i.name FROM stock_movements m JOIN inventory_items i ON i.id=m.item_id AND i.organization_id=m.organization_id WHERE m.organization_id=? ORDER BY m.id DESC LIMIT 30',[org.id])]);
 return <Shell {...shell} path="/inventory" title="The right parts. Ready to go." sub={<p className="page-sub">Track stock by location and put used parts directly into job costs.</p>} actions={<a className="btn" href="/inventory?new=1">+ Add part</a>}><OperationsNav active="/inventory"/><Banner error={q.error} ok={q.ok}/><div className="grid grid-3"><Stat label="Stock value" value={formatMoney(items.reduce((s,i)=>s+i.quantity*i.unitCostCents,0))} note="At recorded unit cost"/><Stat label="Parts tracked" value={String(items.length)} note="Shop and truck stock"/><Stat label="Reorder soon" value={String(items.filter(i=>i.quantity<=i.reorderAt).length)} note="At or below the reorder level"/></div>
 <FormPanel title="Add a part" open={q.new==='1'}><form action={saveInventoryAction} className="form-grid"><Field label="Part name" name="name" required/><Field label="SKU / part number" name="sku"/><Field label="Location" name="location" defaultValue="Shop" placeholder="Shop, Truck 1…"/><Field label="Supplier" name="supplier"/><Field label="Opening quantity" name="quantity" type="number" min="0" step="1" defaultValue="0" required/><Field label="Reorder at" name="reorder_at" type="number" min="0" step="1" defaultValue="2" required/><Field label="Unit cost" name="unit_cost" inputMode="decimal" defaultValue="0.00" required/><Submit>Add part</Submit></form></FormPanel>
 {items.length?<><FormPanel title="Use or receive stock" open={Boolean(q.item)}><form action={moveStockAction} className="form-grid"><input type="hidden" name="mutation_id" value={token()}/><SelectField label="Part" name="item_id" required defaultValue={q.item||''}><option value="" disabled>Choose part</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.location} · {i.quantity} on hand</option>)}</SelectField><SelectField label="Stock change" name="direction" defaultValue="use"><option value="use">Use on a job</option><option value="receive">Receive from supplier</option></SelectField><Field label="Quantity" name="quantity" type="number" min="1" max="100000" step="1" defaultValue="1" required/><SelectField label="Job (required when using stock)" name="job_id"><option value="">Choose job</option>{jobs.filter(j=>j.status!=='cancelled').map(j=><option key={j.id} value={j.id}>{j.title} · {j.customerName}</option>)}</SelectField><Field label="Note / supplier reference" name="note"/><p className="help full">Using stock records its current unit cost on the selected job. Receiving stock increases the quantity on hand.</p><Submit>Record stock change</Submit></form></FormPanel><div className="card ops-table-wrap"><table className="table ops-table"><thead><tr><th>Part</th><th>Location</th><th>On hand</th><th>Reorder at</th><th>Unit cost</th><th>Stock value</th><th/></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.name}</strong><span className="ops-table-sub">{i.sku||i.supplier||'No part number'}</span></td><td>{i.location}</td><td><Pill tone={i.quantity<=i.reorderAt?'warn':'good'}>{i.quantity}</Pill></td><td>{i.reorderAt}</td><td>{formatMoney(i.unitCostCents)}</td><td>{formatMoney(i.unitCostCents*i.quantity)}</td><td><a className="btn btn-secondary btn-sm" href={`/inventory?item=${i.id}`}>Update stock</a></td></tr>)}</tbody></table></div></>:<OpsEmpty title="A stockroom your whole office can see." body="Add the parts you keep on hand. Each use updates stock and records materials on the job."/>}
 {movements.length?<section className="ops-section"><div className="ops-section-head"><h2>Stock activity</h2><span className="muted">Most recent 30 changes</span></div><div className="ops-activity-list">{movements.map(m=><div key={m.id} className="ops-activity-row"><Pill tone={m.delta>0?'good':'neutral'}>{m.delta>0?'+':''}{m.delta}</Pill><div><strong>{m.name}</strong><p>{m.note|| (m.delta>0?'Received':'Used on job')}</p></div>{m.jobId?<a href={`/jobs/${m.jobId}`}>View job</a>:null}<time>{prettyDate(m.createdAt)}</time></div>)}</div></section>:null}</Shell>;
}
