import { agreementStatusAction, agreementVisitAction, saveAgreementAction } from '@/app/operations-actions';
import { Shell } from '@/components/Shell';
import { Banner, Stat } from '@/components/ui';
import { Field, FormPanel, OperationsNav, OpsEmpty, Pill, SelectField, Submit, TextField } from '@/components/OperationsUI';
import { loadApp } from '@/lib/page';
import { getAgreements, rows } from '@/lib/operations';
import { centsToInput, formatMoney } from '@/lib/money';
import { prettyDate } from '@/lib/labels';

export default async function AgreementsPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string;edit?:string;new?:string}>}) {
 const {org,shell}=await loadApp(),q=await searchParams;
 const [plans,customers]=await Promise.all([getAgreements(org.id),rows<{id:number;name:string}>('SELECT id,name FROM customers WHERE organization_id=? AND archived_at IS NULL ORDER BY name',[org.id])]);
 const editing=plans.find(p=>p.id===Number(q.edit)),today=new Date().toISOString().slice(0,10),active=plans.filter(p=>p.status==='active');
 return <Shell {...shell} path="/agreements" title="Keep the next visit on the books." sub={<p className="page-sub">Service plans, renewals, and repeat work in one place.</p>} actions={<a className="btn" href="/agreements?new=1">+ Add service plan</a>}>
 <OperationsNav active="/agreements"/><Banner error={q.error} ok={q.ok}/>
 <div className="grid grid-3"><Stat label="Active plans" value={String(active.length)} note="Customers on recurring service"/><Stat label="Monthly plan value" value={formatMoney(Math.round(active.reduce((sum,p)=>sum+p.amountCents/p.billingMonths,0)))} note="Contract value, before collections"/><Stat label="Visits due" value={String(active.filter(p=>p.nextVisit<=today).length)} note="Ready to put on the schedule"/></div>
 <FormPanel title={editing?'Edit service plan':'Create a service plan'} open={Boolean(editing)||q.new==='1'}><form className="form-grid" action={saveAgreementAction}>
 {editing?<input type="hidden" name="id" value={editing.id}/>:null}<SelectField label="Customer" name="customer_id" required defaultValue={editing?.customerId??''}><option value="" disabled>Choose customer</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</SelectField><Field label="Plan name" name="name" required defaultValue={editing?.name} placeholder="Comfort care membership"/>
 <Field label="Amount per billing period" name="amount" inputMode="decimal" defaultValue={centsToInput(editing?.amountCents||0)} required/><Field label="Billing period (months)" name="billing_months" type="number" min="1" max="36" defaultValue={editing?.billingMonths||1} required/><Field label="Visit every (months)" name="visit_months" type="number" min="1" max="36" defaultValue={editing?.visitMonths||6} required/><Field label="Next visit due" name="next_visit" type="date" defaultValue={editing?.nextVisit||today} required/><Field label="Renewal date" name="renews_on" type="date" defaultValue={editing?.renewsOn}/><TextField label="Included work and terms" name="notes" defaultValue={editing?.notes} placeholder="Two seasonal visits, filter replacement, priority service…"/><p className="help full">Creating a plan tracks the agreement and its visits. Bill through Invoices; automatic recurring charges are not enabled.</p><Submit>Save service plan</Submit></form></FormPanel>
 <div className="ops-plan-grid">{plans.map(p=><article className="ops-plan-card" key={p.id}><div className="row-between"><span className="eyebrow">SERVICE PLAN</span><Pill tone={p.status==='active'?'good':'neutral'}>{p.status}</Pill></div><h2>{p.name}</h2><a href={`/customers/${p.customerId}`} className="ops-customer-link">{p.customerName}</a><div className="ops-plan-price">{formatMoney(p.amountCents)}<span> / {p.billingMonths===1?'month':`${p.billingMonths} months`}</span></div><dl className="ops-facts"><div><dt>Next visit</dt><dd>{prettyDate(p.nextVisit)} {p.status==='active'&&p.nextVisit<=today?<Pill tone="warn">Due</Pill>:null}</dd></div><div><dt>Visit frequency</dt><dd>Every {p.visitMonths} months</dd></div>{p.renewsOn?<div><dt>Renewal</dt><dd>{prettyDate(p.renewsOn)}</dd></div>:null}</dl>{p.notes?<p className="ops-note">{p.notes}</p>:null}<div className="ops-card-actions">{p.status==='active'?<form action={agreementVisitAction}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="occurrence" value={p.nextVisit}/><button className="btn btn-sm">Create next visit</button></form>:null}<a className="btn btn-secondary btn-sm" href={`/agreements?edit=${p.id}`}>Edit</a><form action={agreementStatusAction}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="status" value={p.status==='active'?'paused':'active'}/><button className="btn btn-ghost btn-sm">{p.status==='active'?'Pause':'Resume'}</button></form></div><p className="help">Creating a visit adds an unscheduled job and advances the next due date.</p></article>)}</div>
 {!plans.length?<OpsEmpty title="Turn a good visit into a lasting customer." body="Set up a service plan with its own visit and billing schedule. Sere keeps track of the next visit so it does not slip away."/>:null}</Shell>;
}
