import { saveEquipmentAction } from '@/app/operations-actions';
import { Shell } from '@/components/Shell';
import { Banner, Stat } from '@/components/ui';
import { Field, FormPanel, OperationsNav, OpsEmpty, Pill, SelectField, Submit, TextField } from '@/components/OperationsUI';
import { loadApp } from '@/lib/page';
import { getEquipment, rows } from '@/lib/operations';
import { prettyDate } from '@/lib/labels';

export default async function EquipmentPage({searchParams}:{searchParams:Promise<{error?:string;ok?:string;edit?:string;new?:string;customer?:string}>}) {
 const {org,shell}=await loadApp(),q=await searchParams;
 const [all,customers,properties]=await Promise.all([getEquipment(org.id),rows<{id:number;name:string}>('SELECT id,name FROM customers WHERE organization_id=? AND archived_at IS NULL ORDER BY name',[org.id]),rows<{id:number;customerId:number;name:string;line1:string}>('SELECT id,customer_id,name,line1 FROM properties WHERE organization_id=? ORDER BY line1',[org.id])]);
 const assets=q.customer?all.filter(e=>e.customerId===Number(q.customer)):all,editing=all.find(e=>e.id===Number(q.edit)),today=new Date().toISOString().slice(0,10);
 return <Shell {...shell} path="/equipment" title="Know the system before you arrive." sub={<p className="page-sub">Equipment, warranties, and service dates linked to each customer.</p>} actions={<a className="btn" href="/equipment?new=1">+ Add equipment</a>}><OperationsNav active="/equipment"/><Banner error={q.error} ok={q.ok}/><div className="grid grid-3"><Stat label="Equipment records" value={String(all.length)} note="Across customer properties"/><Stat label="Service due" value={String(all.filter(e=>e.nextService&&e.nextService<=today).length)} note="Review upcoming work"/><Stat label="Under warranty" value={String(all.filter(e=>e.warrantyUntil&&e.warrantyUntil>=today).length)} note="Based on recorded warranty dates"/></div>
 <FormPanel title={editing?'Edit equipment':'Add equipment'} open={Boolean(editing)||q.new==='1'}><form action={saveEquipmentAction} className="form-grid">{editing?<input type="hidden" name="id" value={editing.id}/>:null}<SelectField label="Customer" name="customer_id" defaultValue={editing?.customerId||q.customer||''} required><option value="" disabled>Choose customer</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</SelectField><SelectField label="Property (optional)" name="property_id" defaultValue={editing?.propertyId||''}><option value="">Customer record</option>{properties.map(p=><option key={p.id} value={p.id}>{customers.find(c=>c.id===p.customerId)?.name} · {p.line1||p.name}</option>)}</SelectField><Field label="Equipment name" name="name" required defaultValue={editing?.name} placeholder="Upstairs heat pump"/><Field label="Make and model" name="model" defaultValue={editing?.model}/><Field label="Serial number" name="serial" defaultValue={editing?.serial}/><Field label="Installed on" name="installed_on" type="date" defaultValue={editing?.installedOn}/><Field label="Warranty ends" name="warranty_until" type="date" defaultValue={editing?.warrantyUntil}/><Field label="Next service due" name="next_service" type="date" defaultValue={editing?.nextService}/><TextField label="Service notes" name="notes" defaultValue={editing?.notes}/><Submit>Save equipment</Submit></form></FormPanel>
 <form className="ops-toolbar" method="get"><label>Customer <select name="customer" defaultValue={q.customer||''}><option value="">All customers</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><button className="btn btn-secondary btn-sm">Filter</button>{q.customer?<a href="/equipment">Clear</a>:null}</form>
 <div className="ops-plan-grid">{assets.map(e=><article className="ops-plan-card" key={e.id}><div className="row-between"><span className="eyebrow">EQUIPMENT</span>{e.nextService&&e.nextService<=today?<Pill tone="warn">Service due</Pill>:<Pill>On file</Pill>}</div><h2>{e.name}</h2><a className="ops-customer-link" href={`/customers/${e.customerId}`}>{e.customerName}</a><dl className="ops-facts"><div><dt>Model</dt><dd>{e.model||'—'}</dd></div><div><dt>Serial</dt><dd>{e.serial||'—'}</dd></div><div><dt>Installed</dt><dd>{e.installedOn?prettyDate(e.installedOn):'—'}</dd></div><div><dt>Warranty ends</dt><dd>{e.warrantyUntil?prettyDate(e.warrantyUntil):'—'}</dd></div><div><dt>Next service</dt><dd>{e.nextService?prettyDate(e.nextService):'Not set'}</dd></div></dl>{e.notes?<p className="ops-note">{e.notes}</p>:null}<div className="ops-card-actions"><a className="btn btn-sm" href={`/jobs/new?customerId=${e.customerId}`}>Create service job</a><a className="btn btn-secondary btn-sm" href={`/equipment?edit=${e.id}`}>Edit record</a><a className="btn btn-ghost btn-sm" href={`/customers/${e.customerId}`}>Service history</a></div></article>)}</div>{!assets.length?<OpsEmpty title="The details your next visit needs." body="Record the equipment you service, then keep model numbers, warranty dates, and maintenance notes close to the customer."/>:null}</Shell>;
}
