import { notFound } from 'next/navigation';
import { publicRequestAction } from '@/app/operations-actions';
import { Field, TextField, Submit } from '@/components/OperationsUI';
import { Banner } from '@/components/ui';
import { BrandLogo } from '@/components/BrandLogo';
import { boot } from '@/lib/boot';
import { token } from '@/lib/db';
import { getOperationsSettings, rows } from '@/lib/operations';
export const dynamic='force-dynamic';
export default async function BookingPage({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{sent?:string;error?:string}>}) {
 await boot();const {slug}=await params,q=await searchParams;const [org]=await rows<{id:number;name:string;phone:string;email:string}>('SELECT id,name,phone,email FROM organizations WHERE slug=?',[slug]);if(!org)notFound();const settings=await getOperationsSettings(org.id);
 return <main className="ops-booking"><div className="ops-booking-brand"><BrandLogo className="brand-lockup"/><span>FOR {org.name.toUpperCase()}</span></div><section className="ops-booking-sheet"><span className="ops-eyebrow">{org.name}</span><h1>{q.sent?'You’re on our list.':'Let’s take care of your home.'}</h1><p className="ops-booking-intro">{q.sent?'Your service request has been received. We will get in touch to discuss the work and confirm an appointment.':settings.bookingIntro}</p><Banner error={q.error}/>{q.sent?<a className="btn btn-secondary" href={`/book/${slug}`}>Send another request</a>:settings.bookingEnabled?<form action={publicRequestAction} className="form-grid"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="submission_key" value={token()}/><div className="ops-honeypot" aria-hidden="true"><label>Leave this blank<input name="website" tabIndex={-1} autoComplete="off"/></label></div><Field label="Your name" name="name" required autoComplete="name" maxLength={120}/><Field label="What service do you need?" name="service" required placeholder="Tell us what needs attention" maxLength={200}/><Field label="Email" name="email" type="email" autoComplete="email"/><Field label="Phone" name="phone" type="tel" autoComplete="tel"/><Field label="Service address" name="address" autoComplete="street-address"/><Field label="Preferred date" name="preferred_date" type="date" min={new Date().toISOString().slice(0,10)}/><TextField label="Anything else we should know?" name="description" placeholder="Describe the issue, access instructions, or your preferred time."/><p className="help full">Please provide a phone number or email. We’ll confirm availability before an appointment is booked.</p><Submit>Request service →</Submit></form>:<p>Please contact us directly to book your service.</p>}</section><footer>{settings.serviceArea?<p>Serving {settings.serviceArea}</p>:null}<div className="row">{org.phone?<a href={`tel:${org.phone}`}>{org.phone}</a>:null}{org.email?<a href={`mailto:${org.email}`}>{org.email}</a>:null}</div><p className="tiny mt-2">Powered by Sere</p></footer></main>;
}
